-   id: cropfish
    name: cropfish
    description: The checkboard cropper
    entry: cropfish
    language: python
    always_run: false
    pass_filenames: true
    verbose: false
    types: [image]